#ifndef CONSTANTS_HPP_INCLUDED
#define CONSTANTS_HPP_INCLUDED

// pin mapping

// input
#define PRINTER_INPUT_PIN 22
#define EXTERNAL_VENTILATION_SWITCH_PIN 24

//output
#define PWR_ARDUINO_PIN 37
#define PWR_LIGHT_PIN 29
#define PWR_ENCLOSURE_PIN 31
#define PWR_ENCLOSURE_VENT_PIN 33
#define PWR_EXTERNAL_VENT_PIN 35

// timeouts in ms
#define LEDLIGHTING_TIMEOUT 10000
#define ENCLOSUREPOWER_TIMEOUT 10000
#define ENCLOSUREVENTILATION_TIMEOUT 10000

// tolerances in ms
#define PRINTER_ON_TOLERANCE 3000
#define PRINTER_OFF_TOLERANCE 3000

#endif
