#ifndef CONSTANTS_HPP_INCLUDED
#define CONSTANTS_HPP_INCLUDED

// timeouts in ms
#define LEDLIGHTING_TIMEOUT 10000
#define ENCLOSUREPOWER_TIMEOUT 10000
#define ENCLOSUREVENTILATION_TIMEOUT 10000

// tolerances in ms
#define PRINTER_ON_TOLERANCE 3000
#define PRINTER_OFF_TOLERANCE 3000

#endif
